SAMPLE_RATE = 16_000

CHUNK_SECONDS = 5
OVERLAP_SECONDS = 0.5

CHUNK_SAMPLES = int(SAMPLE_RATE * CHUNK_SECONDS)
OVERLAP_SAMPLES = int(SAMPLE_RATE * OVERLAP_SECONDS)

STEP_SAMPLES = CHUNK_SAMPLES - OVERLAP_SAMPLES
